## -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11([
    "commandEvent",
    "event",
    "eventBroker",
    "eventTypes",
    "eventDequeuer",
    "eventEnqueuer",
    "eventReceiver",
    "eventTransmitter",
    "logEvent",
    "receiver",
    "statusEvent",
    "transmitter",
])
